compilers:
- compiler:
    environment:
      set:
        LD_LIBRARY_PATH: /cvmfs/sft.cern.ch/lcg/contrib/gcc/8binutils/x86_64-slc6/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-e5b21/x86_64-slc6/lib:EXTRA_LIBS
    extra_rpaths:
    - /cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-e5b21/x86_64-slc6/bin
    - /cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-e5b21/x86_64-slc6/lib
    flags:
       # -lrt: in slc6 ldd is taken from the system (GNU libc 2.12), which
       # does not include rt by default, so we need to pass this library.
       # This avoids errors building against Boost for version higher than 1.67
       # * Since glibc 2.17, the library linking -rt is no longer required.
       cppflags: -lrt -std=c++17
    modules: []
    operating_system: scientificcernslc6
    paths:
      cc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/8binutils/x86_64-slc6/bin/gcc
      cxx: /cvmfs/sft.cern.ch/lcg/contrib/gcc/8binutils/x86_64-slc6/bin/g++
      f77: /cvmfs/sft.cern.ch/lcg/contrib/gcc/8binutils/x86_64-slc6/bin/gfortran
      fc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/8binutils/x86_64-slc6/bin/gfortran
    spec: gcc@8.3.0
    target: x86_64
