compilers:
- compiler:
    environment:
      set:
        LD_LIBRARY_PATH: /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2.0binutils/x86_64-slc6/lib64:EXTRA_LIBS
    extra_rpaths:
    - /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.28/x86_64-slc6/lib
    - /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.28/x86_64-slc6/bin
    flags: {}
    modules: []
    operating_system: scientificcernslc6
    paths:
      cc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2.0binutils/x86_64-slc6-gcc62-opt/bin/gcc
      cxx: /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2.0binutils/x86_64-slc6-gcc62-opt/bin/g++
      f77: /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2.0binutils/x86_64-slc6-gcc62-opt/bin/gfortran
      fc: /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2.0binutils/x86_64-slc6-gcc62-opt/bin/gfortran
    spec: gcc@6.2.0
    target: x86_64
