  fcc-edm:
    version: [0.5.2]
  papas:
    version: [1.2.0]
  podio:
    version: [0.8]
  fcc-physics:
    version: [0.2.1]
  acts-core:
    version: [0.07.01]
  heppy:
    version: [v2.0]
  gaudi:
    version: [v29r2]
  tricktrack:
    version: [1.0.6]
