  fccsw:
    version: [develop]
  fcc-edm:
    version: [develop]
  papas:
    version: [develop]
  podio:
    version: [develop]
  acts-core:
    version: [develop]
  heppy:
    version: [develop]
  gaudi:
    version: [v29r2]
  tricktrack:
    version: [develop]
