  fccsw:
    version: [v0.12]
  fcc-edm:
    version: [0.5.5]
  fcc-edm-legacy:
    version: [0.1.1]
  papas:
    version: [1.2.2]
  heppy:
    version: [2.1]
  py-fcchhanalyses:
    version: [0.1.1]
  guinea-pig:
    version: [1.2.2rc]
