  fccsw:
    version: [develop]
  fcc-edm:
    version: [develop]
  papas:
    version: [develop]
  podio:
    version: [develop]
  acts-core:
    version: [0.07.01]
  heppy:
    version: [v2.0]
  gaudi:
    version: [v29r2]
  tricktrack:
    version: [1.0.6]
